# Dependencies
markdown: redcarpet
highlighter: pygments 

# Permalinks
permalink: pretty

# Setup
title: Devon Walker
url: http://devonwa.com
base_url: /
author:
  name: Devon Walker
  url: https://twitter.com/devwalker
  email: devon@devonwa.com
paginate: 5

# Custom vars
version:
  bootstrap_css: 3.2.0
  bootstrap_js: 3.2.0
  fontawesome: 4.2.0
social_url:
  twitter: https://twitter.com/devwalk
  github: https://github.com/devonwa
  facebook: 
  google_plus: 

