# Site vars
name: "Devon Walker"
url: http://devonwa.com
highlighter: pygments
lsi: false
markdown: kramdown
permalink: pretty
paginate: 5
encoding: utf-8

# Custom vars
version:
  bootstrap_css: 3.2.0
  bootstrap_js: 3.2.0
  fontawesome: 4.2.0
