# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Devon Walker
url:              http://devonwa.com
paginate:         1
baseurl:          /
author:
  name:           Devon WAlker
  url:            https://twitter.com/devwalker
  email:          devon@devonwa.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/devonwa/devonwa.github.io
