# RSS
name: devonwa.com
description: An engineering blog by Devon Walker.
url: http://devonwa.com

# Site vars
highlighter: pygments
lsi: false
markdown: kramdown
permalink: pretty

# Custom vars
version:
  bootstrap_css: 3.2.0
  bootstrap_js: 3.2.0
  fontawesome: 4.2.0
